### ISSUE TITLE
Not recognizing all matching images

### ISSUE THREAD

**Issue by C-Loftus** [splondike/talon_ui_helper#3]
I am using option  2 from the command wizard ' show markers on all image matches on the screen'. I'm trying to use this to control the vscode file explorer  based on the drop down image next to each directory.It works for most directories but not all for some reason. I wasn't sure why this was the case.

 I have included an image of the file explorer directory structure with the letters that are generated from the helper.  the code below was generated from option 2. The image referenced is simply the small triangle which represents the directory, I made sure not to include any text or other extra noise.

  Thank you very much for your work on this tool!

![image](https://user-images.githubusercontent.com/70598503/169928486-04ee0df2-1386-4240-84a6-157fbfff346b.png)

```
navigate explorer:
    matches = user.mouse_helper_find_template_relative("2022-05-23_17.26.01.390459.png")
    user.marker_ui_show(matches)
```

**Comment by splondike** [comment]
As mentioned in Slack, your experience is potentially related to this Talon beta issue: https://github.com/talonvoice/talon/issues/456 .

That said, I wasn't able to reproduce this with my Linux version of VSCode and the latest beta. Would you be able to upload the `2022-05-23_17.26.01.390459.png` template file you're using and also a screencapture of your VSCode without the markers showing? This should let me reproduce the issue. Just double check you do actually get the issue with the VSCode window you have showing.
